
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'app.title': '开发者中心',
    'nav.docs': '文档',
    'nav.changelog': '更新日志',
    'nav.api': 'API 参考',
    'nav.community': '社区',
    'nav.console': '管理控制台',
    'nav.logout': '退出',
    'nav.login': '登录',
    'header.consoleBadge': '控制台',
    'header.clickToEdit': '点击编辑',
    'search.placeholder': '搜索文档...',
    'sidebar.title': '文档目录',
    'doc.lastUpdated': '最后更新：',
    'doc.helpful.title': '这篇文档对你有帮助吗？',
    'doc.helpful.yes': '有帮助',
    'doc.helpful.no': '没帮助',
    'doc.helpful.thanks': '感谢您的反馈！',
    'doc.notFound': '页面未找到',
    'doc.notFoundDesc': '您正在寻找的文档不存在，或者已被删除。',
    'doc.returnHome': '返回首页',
    'admin.backToDashboard': '返回概览',
    'admin.saved': '已保存！',
    'admin.saveConfig': '保存配置',
    'admin.dashboard.title': '内容管理',
    'admin.dashboard.subtitle': '管理文档、更新日志和开发指南。',
    'admin.dashboard.system': '系统管理',
    'admin.dashboard.manage': '进入管理',
    'admin.newDoc': '新建文档',
    'admin.viewSite': '查看站点',
    'admin.menus': '菜单管理',
    'admin.users': '账号管理',
    'admin.products': '产品线管理',
    'admin.wechat': '微信集成',
    'admin.ai': 'AI 配置',
    'admin.searchPlaceholder': '搜索文档...',
    'admin.table.title': '标题',
    'admin.table.status': '状态',
    'admin.table.lastUpdated': '最后更新',
    'admin.table.actions': '操作',
    'admin.table.feedback': '反馈数据',
    'admin.noDocs': '未找到文档。',
    'admin.deleteConfirm': '确定要删除此项吗？',
    'admin.batchDeleteConfirm': '确定要删除选中的 {count} 个文档吗？此操作不可恢复。',
    'admin.batchDelete': '批量删除',
    'admin.select': '选择',
    'admin.selectAll': '全选',
    'admin.editor.createTitle': '创建文档',
    'admin.editor.editTitle': '编辑文档',
    'admin.editor.aiAssist': 'AI 助手',
    'admin.editor.history': '版本历史',
    'admin.editor.cancel': '取消',
    'admin.editor.save': '保存更改',
    'admin.editor.saveVersion': '保存版本',
    'admin.editor.saving': '保存中...',
    'admin.editor.field.title': '标题',
    'admin.editor.field.slug': '路径 (URL)',
    'admin.editor.field.product': '所属产品',
    'admin.editor.field.topNav': '顶部导航',
    'admin.editor.field.category': '分类',
    'admin.editor.field.version': '版本号',
    'admin.editor.field.status': '状态',
    'admin.editor.selectTab': '选择导航...',
    'admin.editor.selectCategory': '选择分类...',
    'admin.editor.selectProduct': '选择产品...',
    'admin.editor.contentLabel': 'Markdown 内容',
    'admin.editor.placeholder': '# 在此开始编写文档...',
    'admin.history.title': '版本记录',
    'admin.history.restore': '回滚',
    'admin.history.restoreConfirm': '确定要回滚到此版本吗？当前未保存的内容将丢失。',
    'admin.history.empty': '暂无历史版本',
    'admin.ai.title': 'AI 助手',
    'admin.ai.desc': '描述您想对内容进行的操作（例如："修复语法"、"翻译成英文"、"添加关于错误代码的章节"）。',
    'admin.ai.placeholder': '输入您的指令...',
    'admin.ai.generate': '生成',
    'admin.ai.thinking': '思考中...',
    'admin.ai.error': 'AI 生成失败，请检查 API 配置。',
    'admin.menus.title': '菜单配置',
    'admin.menus.subtitle': '配置顶部导航和左侧侧边栏结构',
    'admin.menus.topNav': '顶部导航',
    'admin.menus.sidebar': '侧边栏分类',
    'admin.menus.selectProduct': '选择要管理的产品分类：',
    'admin.menus.add': '添加项',
    'admin.menus.label': '标签 (或翻译键)',
    'admin.menus.path': '路径',
    'admin.menus.order': '排序',
    'admin.menus.parent': '父级分类',
    'admin.menus.name': '名称',
    'admin.menus.deleteConfirm': '确定删除吗？此操作无法撤销。',
    'admin.menus.noItems': '暂无数据',
    'admin.menus.back': '返回概览',
    'admin.menus.scope': '1. 选择产品范围',
    'admin.menus.configureTop': '2. 配置顶部导航',
    'admin.menus.configureSide': '3. 配置侧边栏',
    'admin.menus.noneRoot': '(无 - 根节点)',
    'admin.users.title': '账号管理',
    'admin.users.subtitle': '管理控制台访问权限和角色',
    'admin.users.username': '用户名',
    'admin.users.displayName': '显示名称',
    'admin.users.role': '角色',
    'admin.users.role.guest': '游客',
    'admin.users.role.editor': '编辑',
    'admin.users.role.admin': '管理员',
    'admin.users.status': '状态',
    'admin.users.password': '密码',
    'admin.users.add': '添加用户',
    'admin.users.error': '用户名和密码为必填项',
    'admin.users.status.PENDING': '待审核',
    'admin.users.status.ACTIVE': '已激活',
    'admin.users.approve': '通过审核',
    'admin.products.title': '产品线管理',
    'admin.products.subtitle': '添加或编辑不同的产品模块（如小程序、视频号）',
    'admin.products.add': '添加产品',
    'admin.products.name': '产品名称',
    'admin.products.id': 'ID (唯一标识)',
    'admin.products.error': '名称和 ID 为必填项',
    'admin.wechat.title': '微信集成配置',
    'admin.wechat.subtitle': '配置公众号或开放平台接口信息',
    'admin.wechat.sectionTitle': '微信公众号/开放平台',
    'admin.wechat.sectionDesc': '连接微信生态系统，实现扫码登录与消息推送',
    'admin.wechat.appId': 'AppID',
    'admin.wechat.appSecret': 'AppSecret',
    'admin.wechat.token': 'Token (令牌)',
    'admin.wechat.aesKey': 'EncodingAESKey',
    'admin.wechat.callback': '服务器地址 (URL)',
    'admin.wechat.callbackHint': '请在微信公众平台后台配置此 URL。',
    'admin.wechat.enable': '启用微信登录与集成',
    'admin.aiconfig.title': 'AI 服务配置',
    'admin.aiconfig.subtitle': '连接 Google Gemini 或 阿里百炼 以启用智能功能',
    'admin.aiconfig.enable': '启用 AI 功能',
    'admin.aiconfig.provider': '服务提供商',
    'admin.aiconfig.apiKey': 'API Key',
    'admin.aiconfig.model': '模型名称 (Model)',
    'admin.aiconfig.baseUrl': 'Base URL (可选)',
    'admin.aiconfig.baseUrlHint': '仅 Bailian/OpenAI 模式需要，例如 https://dashscope.aliyuncs.com/compatible-mode/v1',
    'admin.aiconfig.geminiHint': '留空则使用默认 gemini-3-flash-preview',
    'admin.aiconfig.bailianHint': '留空则使用默认 qwen-turbo',
    'login.title': '控制台登录',
    'login.subtitle': '输入凭据以访问后台',
    'login.password': '密码',
    'login.signin': '登录',
    'login.demo': '演示账号：',
    'login.error': '用户名或密码错误',
    'login.error.pending': '账号正在审核中，请耐心等待管理员批准。',
    'login.register': '创建账号',
    'login.registerLink': '没有账号？立即注册',
    'login.registerSubtitle': '加入开发者社区',
    'login.bind': '绑定微信',
    'login.bindSubtitle': '绑定账号以快速访问',
    'login.bindSuccess': '注册成功',
    'login.bindDesc': '请使用微信扫码绑定账号，以便日后快速登录。',
    'login.pendingTitle': '注册成功，等待审核',
    'login.pendingDesc': '您的账号已创建。为了安全起见，所有新账号都需要管理员审核通过后方可激活。请联系管理员或耐心等待。',
    'login.scan': '扫码登录',
    'login.scanTip': '请使用微信扫一扫',
    'login.scanSuccess': '登录成功',
    'login.scanWait': '正在登录...',
    'login.next': '下一步',
    'login.complete': '完成注册',
    'login.back': '返回登录',
    'login.skip': '暂时跳过',
    'login.noBindAccount': '未找到绑定该微信的账号，请先注册。',
    'auth.restricted': '访问受限',
    'auth.loginRequired': '请登录以查看此文档。',
    'status.DRAFT': '草稿',
    'status.PUBLISHED': '已发布',
    'status.ARCHIVED': '已归档',
    'modal.deleteTitle': '确认删除',
    'modal.confirm': '删除',
    'modal.alertTitle': '提示',
    'modal.successTitle': '成功',
    'modal.ok': '确定',
    'admin.upload.title': '批量上传文档',
    'admin.upload.subtitle': '上传 Markdown 文件并分配到指定分类',
    'admin.upload.dropzone': '点击或拖拽上传 .md 文件',
    'admin.upload.selected': '个文件已选择',
    'admin.upload.config': '目标位置配置',
    'admin.upload.submit': '开始上传',
    'admin.upload.success': '文档上传成功！',
    'admin.upload.error': '请填写所有必选项',
    'admin.upload.processing': '处理中...',
    'admin.upload.noFiles': '未选择文件',
    'admin.upload.failed': '上传失败',
    'admin.pdf.title': '导入 PDF 文档',
    'admin.pdf.subtitle': '使用 AI 将 PDF 手册转换为结构化的 Markdown 文档。',
    'admin.pdf.targetProduct': '目标产品',
    'admin.pdf.targetTab': '目标导航',
    'admin.pdf.dropzone': '点击或拖拽上传 PDF 文件',
    'admin.pdf.analyzing': 'AI 正在分析您的 PDF...',
    'admin.pdf.analyzingDesc': '正在提取文本、构建目录并转换为 Markdown，请稍候。',
    'admin.pdf.complete': '分析完成！发现 {count} 个文档。',
    'admin.pdf.import': '导入 {count} 个文档',
    'admin.pdf.analyze': '开始 AI 分析',
    'admin.pdf.error': '请选择文件、产品和目标导航。',
    'admin.pdf.fail': 'Failed to analyze PDF. Please try again or use a smaller file.',
    'admin.pdf.clickToChange': '点击更换文件',
    'admin.pdf.clickToUpload': '点击上传 PDF',
    'admin.pdf.maxPages': '仅演示前 20 页',
    'admin.pdf.success': 'PDF 导入成功！',
    'admin.allProducts': '所有产品',
    'chat.title': '智能助手',
    'chat.placeholder': '问点什么关于文档的内容...',
    'chat.welcome': '你好！我是开发者中心助手。我可以根据现有文档回答你的问题。',
    'chat.thinking': '思考中...',
    'chat.error': '抱歉，我遇到了一些问题。',
  },
  en: {
    'app.title': 'DevCenter',
    'nav.docs': 'Docs',
    'nav.changelog': 'Changelog',
    'nav.api': 'API Reference',
    'nav.community': 'Community',
    'nav.console': 'Console',
    'nav.logout': 'Logout',
    'nav.login': 'Log In',
    'header.consoleBadge': 'Console',
    'header.clickToEdit': 'Click to Edit',
    'search.placeholder': 'Search documentation...',
    'sidebar.title': 'Documentation',
    'doc.lastUpdated': 'Last updated:',
    'doc.helpful.title': 'Was this document helpful?',
    'doc.helpful.yes': 'Yes, it helped',
    'doc.helpful.no': 'No, I need more info',
    'doc.helpful.thanks': 'Thanks for your feedback!',
    'doc.notFound': 'Page Not Found',
    'doc.notFoundDesc': 'The documentation you are looking for does not exist or has been deleted.',
    'doc.returnHome': 'Return Home',
    'admin.backToDashboard': 'Back to Dashboard',
    'admin.saved': 'Saved!',
    'admin.saveConfig': 'Save Configuration',
    'admin.dashboard.title': 'Content Management',
    'admin.dashboard.subtitle': 'Manage documentation, changelogs, and guides.',
    'admin.dashboard.system': 'System Management',
    'admin.dashboard.manage': 'Manage',
    'admin.newDoc': 'New Document',
    'admin.viewSite': 'View Site',
    'admin.menus': 'Menu Management',
    'admin.users': 'User Management',
    'admin.products': 'Product Management',
    'admin.wechat': 'WeChat Config',
    'admin.ai': 'AI Config',
    'admin.searchPlaceholder': 'Search documents...',
    'admin.table.title': 'Title',
    'admin.table.status': 'Status',
    'admin.table.lastUpdated': 'Last Updated',
    'admin.table.actions': 'Actions',
    'admin.table.feedback': 'Feedback',
    'admin.noDocs': 'No documents found.',
    'admin.deleteConfirm': 'Are you sure you want to delete this item?',
    'admin.batchDeleteConfirm': 'Are you sure you want to delete {count} items? This cannot be undone.',
    'admin.batchDelete': 'Batch Delete',
    'admin.select': 'Select',
    'admin.selectAll': 'Select All',
    'admin.editor.createTitle': 'Create Document',
    'admin.editor.editTitle': 'Edit Document',
    'admin.editor.aiAssist': 'AI Assist',
    'admin.editor.history': 'History',
    'admin.editor.cancel': 'Cancel',
    'admin.editor.save': 'Save Changes',
    'admin.editor.saveVersion': 'Save Version',
    'admin.editor.saving': 'Saving...',
    'admin.editor.field.title': 'Title',
    'admin.editor.field.slug': 'Slug (URL)',
    'admin.editor.field.product': 'Product',
    'admin.editor.field.topNav': 'Top Navigation Tab',
    'admin.editor.field.category': 'Category',
    'admin.editor.field.version': 'Version',
    'admin.editor.field.status': 'Status',
    'admin.editor.selectTab': 'Select Tab...',
    'admin.editor.selectCategory': 'Select Category...',
    'admin.editor.selectProduct': 'Select Product...',
    'admin.editor.contentLabel': 'Markdown Content',
    'admin.editor.placeholder': '# Start writing your documentation here...',
    'admin.history.title': 'Version History',
    'admin.history.restore': 'Restore',
    'admin.history.restoreConfirm': 'Are you sure you want to restore this version? Current unsaved changes will be lost.',
    'admin.history.empty': 'No version history.',
    'admin.ai.title': 'AI Assistant',
    'admin.ai.desc': 'Describe what you want to do with the content (e.g., "Fix grammar", "Translate to English", "Add a section about Error Codes").',
    'admin.ai.placeholder': 'Enter your instruction...',
    'admin.ai.generate': 'Generate',
    'admin.ai.thinking': 'Thinking...',
    'admin.ai.error': 'AI Generation failed. Please check your API configuration.',
    'admin.menus.title': 'Menu Configuration',
    'admin.menus.subtitle': 'Configure top navigation and sidebar structure',
    'admin.menus.topNav': 'Top Navigation',
    'admin.menus.sidebar': 'Sidebar Categories',
    'admin.menus.selectProduct': 'Select Product to manage categories:',
    'admin.menus.add': 'Add Item',
    'admin.menus.label': 'Label (or key)',
    'admin.menus.path': 'Path',
    'admin.menus.order': 'Order',
    'admin.menus.parent': 'Parent Category',
    'admin.menus.name': 'Name',
    'admin.menus.deleteConfirm': 'Are you sure? This action cannot be undone.',
    'admin.menus.noItems': 'No items found',
    'admin.menus.back': 'Back to Dashboard',
    'admin.menus.scope': '1. Select Product Scope',
    'admin.menus.configureTop': '2. Configure Top Navigation',
    'admin.menus.configureSide': '3. Configure Sidebar',
    'admin.menus.noneRoot': '(None - Root)',
    'admin.users.title': 'User Management',
    'admin.users.subtitle': 'Manage console access and roles',
    'admin.users.username': 'Username',
    'admin.users.displayName': 'Display Name',
    'admin.users.role': 'Role',
    'admin.users.role.guest': 'Guest',
    'admin.users.role.editor': 'Editor',
    'admin.users.role.admin': 'Admin',
    'admin.users.status': 'Status',
    'admin.users.password': 'Password',
    'admin.users.add': 'Add User',
    'admin.users.error': 'Username and Password are required',
    'admin.users.status.PENDING': 'Pending',
    'admin.users.status.ACTIVE': 'Active',
    'admin.users.approve': 'Approve',
    'admin.products.title': 'Product Management',
    'admin.products.subtitle': 'Add or edit product modules (e.g. Mini Programs, Channels)',
    'admin.products.add': 'Add Product',
    'admin.products.name': 'Product Name',
    'admin.products.id': 'ID (Unique)',
    'admin.products.error': 'Name and ID are required',
    'admin.wechat.title': 'WeChat Configuration',
    'admin.wechat.subtitle': 'Configure Official Account or Open Platform settings',
    'admin.wechat.sectionTitle': 'WeChat Official Account',
    'admin.wechat.sectionDesc': 'Connect your platform with WeChat ecosystem',
    'admin.wechat.appId': 'AppID',
    'admin.wechat.appSecret': 'AppSecret',
    'admin.wechat.token': 'Token',
    'admin.wechat.aesKey': 'EncodingAESKey',
    'admin.wechat.callback': 'Server URL',
    'admin.wechat.callbackHint': 'Configure this URL in WeChat Admin Console.',
    'admin.wechat.enable': 'Enable WeChat Login & Integration',
    'admin.aiconfig.title': 'AI Service Config',
    'admin.aiconfig.subtitle': 'Connect Google Gemini or Ali Bailian for intelligent features',
    'admin.aiconfig.enable': 'Enable AI Features',
    'admin.aiconfig.provider': 'Service Provider',
    'admin.aiconfig.apiKey': 'API Key',
    'admin.aiconfig.model': 'Model Name',
    'admin.aiconfig.baseUrl': 'Base URL (Optional)',
    'admin.aiconfig.baseUrlHint': 'Required for Bailian/OpenAI, e.g. https://dashscope.aliyuncs.com/compatible-mode/v1',
    'admin.aiconfig.geminiHint': 'Leave empty for default gemini-3-flash-preview',
    'admin.aiconfig.bailianHint': 'Leave empty for default qwen-turbo',
    'login.title': 'Console Login',
    'login.subtitle': 'Enter your credentials to access the dashboard',
    'login.password': 'Password',
    'login.signin': 'Sign In',
    'login.demo': 'Demo accounts:',
    'login.error': 'Invalid username or password',
    'login.error.pending': 'Account pending approval. Please wait for admin activation.',
    'login.register': 'Create Account',
    'login.registerLink': 'No account? Register now',
    'login.registerSubtitle': 'Join our developer community',
    'login.bind': 'Bind WeChat',
    'login.bindSubtitle': 'Secure your account for quick access',
    'login.bindSuccess': 'Registration Successful',
    'login.bindDesc': 'Please scan with WeChat to bind your account. This enables quick login in the future.',
    'login.pendingTitle': 'Registration Pending',
    'login.pendingDesc': 'Your account has been created successfully. For security reasons, all new accounts require administrator approval before activation.',
    'login.scan': 'Scan Code',
    'login.scanTip': 'Open WeChat to scan',
    'login.scanSuccess': 'Login Successful',
    'login.scanWait': 'Logging in...',
    'login.next': 'Next Step',
    'login.complete': 'Complete Registration',
    'login.back': 'Back to Login',
    'login.skip': 'Skip binding for now',
    'login.noBindAccount': 'No account found bound to this WeChat. Please register first.',
    'auth.restricted': 'Access Restricted',
    'auth.loginRequired': 'Please log in to view this documentation.',
    'status.DRAFT': 'Draft',
    'status.PUBLISHED': 'Published',
    'status.ARCHIVED': 'Archived',
    'modal.deleteTitle': 'Confirm Delete',
    'modal.confirm': 'Delete',
    'modal.alertTitle': 'Alert',
    'modal.successTitle': 'Success',
    'modal.ok': 'OK',
    'admin.upload.title': 'Batch Upload Docs',
    'admin.upload.subtitle': 'Upload Markdown files and assign to a category',
    'admin.upload.dropzone': 'Click or drag .md files here',
    'admin.upload.selected': 'files selected',
    'admin.upload.config': 'Destination Configuration',
    'admin.upload.submit': 'Start Upload',
    'admin.upload.success': 'Documents uploaded successfully!',
    'admin.upload.error': 'Please complete all required fields',
    'admin.upload.processing': 'Processing...',
    'admin.upload.noFiles': 'No files selected',
    'admin.upload.failed': 'Upload failed',
    'admin.pdf.title': 'Import PDF to Docs',
    'admin.pdf.subtitle': 'Convert PDF manuals into structured Markdown docs using AI.',
    'admin.pdf.targetProduct': 'Target Product',
    'admin.pdf.targetTab': 'Target Tab',
    'admin.pdf.dropzone': 'Click to upload PDF',
    'admin.pdf.analyzing': 'AI is analyzing your PDF...',
    'admin.pdf.analyzingDesc': 'AI is extracting text, structuring categories, and converting content to Markdown. This may take a moment.',
    'admin.pdf.complete': 'Analysis Complete! Found {count} documents.',
    'admin.pdf.import': 'Import {count} Docs',
    'admin.pdf.analyze': 'Analyze with AI',
    'admin.pdf.error': 'Please select a file, product, and target navigation tab.',
    'admin.pdf.fail': 'Failed to analyze PDF. Please try again or use a smaller file.',
    'admin.pdf.clickToChange': 'Click to change file',
    'admin.pdf.clickToUpload': 'Click to upload PDF',
    'admin.pdf.maxPages': 'Maximum 20 pages will be analyzed for demo',
    'admin.pdf.success': 'PDF Imported Successfully!',
    'admin.allProducts': 'All Products',
    'chat.title': 'AI Assistant',
    'chat.placeholder': 'Ask something about the documentation...',
    'chat.welcome': 'Hello! I am the DevCenter Assistant. I can answer questions based on the existing documentation.',
    'chat.thinking': 'Thinking...',
    'chat.error': 'Sorry, I encountered an issue.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[language][key] || key;
    if (params) {
        Object.keys(params).forEach(k => {
            text = text.replace(`{${k}}`, params[k]);
        });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};